name: 'Infraestructura CI/CD'

on:
  push:
    branches: [ feature/*, master ]
    # paths:
    #   - 'infra/**'
  pull_request:
    branches: [ master ]
    # paths:
    #   - 'infra/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  pre-commit:
    name: 'Pre-commit Terraform Checks'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
    defaults:
      run:
        working-directory: ./infra
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Setup pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ hashFiles('./infra/.pre-commit-config.yaml') }}

      - name: Create pre-commit config file if not exists
        run: |
          if [ ! -f ".pre-commit-config.yaml" ]; then
            cat > .pre-commit-config.yaml << 'EOF'
            repos:
            - repo: https://github.com/antonbabenko/pre-commit-terraform
              rev: v1.83.5
              hooks:
                - id: terraform_fmt
                - id: terraform_validate
                - id: terraform_docs
                - id: terraform_providers_lock
                  args:
                    - --args=-platform=darwin_arm64
                    - --args=-platform=darwin_amd64
                    - --args=-platform=linux_amd64
            - repo: https://github.com/pre-commit/pre-commit-hooks
              rev: v4.4.0
              hooks:
                - id: check-merge-conflict
                - id: end-of-file-fixer
                - id: trailing-whitespace
                - id: check-yaml
            EOF
          fi

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --color=always --show-diff-on-failure


  terraform-ci:
    name: 'Terraform CI'
    needs: [pre-commit]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost baseline
        run: infracost breakdown --path . --format json --out-file infracost-base.json

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

  terraform-cd:
    name: 'Terraform CD'
    needs: terraform-ci
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
